### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by loggerhead** [loggerhead/Layout#1]
- [x] resize pane (remove ruler when destroy if necessary)
- [x] save as layout file
- [x] load from layout file
- [x] undo pane move
- [x] undo split pane 
- [ ] ~~allow auto close when carry away or close last view~~
- [x] allow auto close view when pane destroyed
- [ ] don't change previous cursor position when move between panes
- [ ] ~~show pane group~~
- [ ] ~~refactor by using tree~~
- [ ] combine two kind of undo operation
- [ ] ~~create layout by diagram (like markdown table grammar)~~
- [ ] add select menu from .layout
